### ISSUE TITLE
GenericMeasurement sent by a Sentuator have no performative and no recipient

### ISSUE THREAD

**Issue by notthetup** [org-arl/fjage-sentuator#7] opened 2021-07-07 08:50 UTC
It seems that if a sentuator returns a `GenericMeasurement` when it receives a `MeasurementReq` or when it's polling, the `GenericMeasurement` doesn't seem to have a performative or a recipient.

Some of the JSON messages were received by the client when a few sentuators were set to poll regularly.

```
{"action":"send","message":{"clazz":"org.arl.fjage.sentuator.GenericMeasurement","data":{"leak":{"value":0.0,"units":""}}},"relay":false}	138	
16:44:17.691
{"action":"send","message":{"clazz":"org.arl.fjage.sentuator.GenericMeasurement","data":{"efuse1-current":{"value":0.0,"units":"mA"},"efuse1-power":{"value":1,"units":""},"efuse1-enable":{"value":1,"units":""}}},"relay":false}	227	
16:44:18.671
{"action":"send","message":{"clazz":"org.arl.fjage.sentuator.GenericMeasurement","data":{"leak":{"value":0.0,"units":""}}},"relay":false}	138	
16:44:18.691
{"action":"send","message":{"clazz":"org.arl.fjage.sentuator.GenericMeasurement","data":{"efuse1-current":{"value":0.0,"units":"mA"},"efuse1-power":{"value":1,"units":""},"efuse1-enable":{"value":1,"units":""}}},"relay":false}	227	
16:44:19.670
{"action":"send","message":{"clazz":"org.arl.fjage.sentuator.GenericMeasurement","data":{"leak":{"value":0.0,"units":""}}},"relay":false}
```

**Comment by mchitre** [comment] 2021-07-07 20:00
Not sure I understand what you mean. If the message doesn't have a recipient, how did you see it to know it didn't have a performative? Maybe some steps to reproduce the problem would be useful.

**Comment by notthetup** [comment] 2021-07-08 06:14
Measurements sent out by the Sentuator should have a `recipient`. If sent because of the internal polling mechanism, it will have the recipient set to the notification topic 

https://github.com/org-arl/fjage-sentuator/blob/master/src/main/groovy/org/arl/fjage/sentuator/Sentuator.groovy#L147

otherwise in the case of a `MeasurementReq,` the `recipient` is the sender of the `MeasurementReq`.

But I am not seeing either. But I have figured out what is happening.

These are sentuators running in a `fjage` Master container which are connected to another `fjage` Master container over a custom "wormhole" which rebroadcasts the fjåge messages between them through a UDP connection. I'm logging the JSON received at a Slave container (Gateway) which is connected to this 2nd Master container.

I am guessing (I need to verify) the 2nd Master container doesn't have the `fjage-sentuator.jar`. So when the messages coming in on the UDP connection are inflated, since no class can be found, they are inflated as `GenericMessage` and hence they lose some of the information. These are then sent to the Slave as usual which I then print out.

The solution should be to add `fjage-sentuator.jar` to the second master container.

**Comment by notthetup** [comment] 2021-07-10 09:32
OK. I managed to make a MWE.

Simple fjage+fjage-sentuator setup.

`fjage-1.9.1-SNAPSHOT.jar` and `fjage-sentuator-1.2.1.jar`

Running with this script..

```
import org.arl.fjage.*
import org.arl.fjage.remote.*
import org.arl.fjage.shell.*
import org.arl.fjage.connectors.*
import org.arl.fjage.sentuator.*

int port = 5081

platform = new RealTimePlatform()
container = new MasterContainer(platform, port)
WebServer.getInstance(8080).add("/fjage", "/org/arl/fjage/web")
Connector conn = new WebSocketConnector(8080, "/fjage/shell/ws")
shell = new ShellAgent(new ConsoleShell(conn), new GroovyScriptEngine())

class MySentuator extends Sentuator {

  void setup() {
    sentuatorName = 'Demo Sentuator'    // name your sentuator
    config.ofs = 0.0                    // setup your configuration parameters
    setPoll(1000)
    setEnable(true)
  }

  Measurement measure() {
    // generate a random measurement with the configured offset
    def m = new GenericMeasurement(type: sentuatorName)
    m.x = new Quantity(Math.random() + config.ofs, 'm')
    return m
  }

}

container.add 'mysen', new MySentuator()

logLevel 'org.arl.fjage.remote', FINEST

container.add 'shell', shell
platform.start()
```

Open a connection to this master container using `nc` : `nc localhost 5081` and look at the messages being sent out..

```
1625909462028|FINE|org.arl.fjage.remote.ConnectionHandler@30:println|tcp:///0:0:0:0:0:0:0:1:5081//0:0:0:0:0:0:0:1.54267 >>> {"action":"send","message":{"clazz":"org.arl.fjage.sentuator.GenericMeasurement","data":{"x":{"value":0.8881724247695482,"units":"m"}}},"relay":false}
```

**Comment by notthetup** [comment] 2021-07-10 09:41
It seems somehow the JSON-ification of a `GenericMessage` has some issues. Could it have something to do with 

`class GenericMeasurement extends Measurement implements Map<String,Quantity>`

https://github.com/org-arl/fjage-sentuator/blob/master/src/main/groovy/org/arl/fjage/sentuator/GenericMeasurement.groovy#L9

**Comment by mchitre** [comment] 2021-07-11 02:53
Yes, quite likely. Since the `GenericMeasurement` implements a `Map`, GSON probably just treats it as a map and serializes only the map keys. Either we'll need to set an adapter to include it, or we can expose the standard properties (`performative`, `recipient`, `inReplyTo`, `messageID`, etc) in the `Map` interface.

**Comment by notthetup** [comment] 2021-07-11 04:59
Would it work by annotating GenericMeasurement to use the same Adapter as fjage `GenericMessage` ? Since there we have that logic already?

**Comment by mchitre** [comment] 2021-07-12 20:38
`GenericMessage` is actually handled as a special case in `MessageAdapterFactory`. We'd need to change that in fjåge source code, so that wouldn't work.

**Comment by notthetup** [comment] 2021-07-13 01:57
Indeed. Another option is to make `GenericMessage` a subclass of `GenericMessage`, that way the special case handling will get triggered?

**Comment by mchitre** [comment] 2021-07-13 05:01
No multiple inheritance in Java. Probably easier to go with exposing standard properties as map properties.

**Comment by mchitre** [comment] 2021-07-29 16:29
I explored quite a few possibilities, and eventually settled for a hybrid solution. The `GenericMeasurement` class no longer implements `Map` and so JSON serialization problems are avoided. However, in dynamic Groovy code, we still support the property style syntax `msg.x = y` using Groovy's MOP. For static Groovy code or Java code, we have to use the `set()` and `get()` methods instead.

**Comment by mchitre** [comment] 2021-07-29 16:35
@notthetup I have done preliminary testing and this seems OK. Can you please cross-check, and if all OK, close it?

**Comment by notthetup** [comment] 2021-07-30 04:42
I believe this might break some dependents that use the `Map` interface in static Groovy code. This should be a major version bump.

**Comment by ngyewch** [comment] 2021-09-16 07:20
+1 to this. I'm getting reports from external users about this.

**Comment by mchitre** [comment] 2021-09-17 01:45
@ngyewch what version of fjåge and fjåge senator are the external users using?

**Comment by ngyewch** [comment] 2021-09-17 01:54
That would most likely be tied to what Unet (C3) depends on.

**Comment by mchitre** [comment] 2021-09-17 02:04
Are they using UnetC3 `3.3.0-beta1 pre-release` from the `c3-users` repo, or `3.4.0-SNAPSHOT` from the `artifacts` repo?

**Comment by ngyewch** [comment] 2021-09-17 02:37
I've updated https://github.com/ngyewch/fjage-sentuator-configparam-test (which only depends on fjage 1.9.1, fjage-sentuator-1.2.1, no unet).

See https://github.com/ngyewch/fjage-sentuator-configparam-test/blob/7600d0046b5a9bde067f1bad055cb876b2793a25/src/test/java/JsonTests.java#L35-L53

**Comment by mchitre** [comment] 2021-09-26 11:43
@notthetup did you ever get a chance to check this fix?

**Comment by notthetup** [comment] 2021-09-27 01:51
Sorry. I missed out to test this.

I tried the MWE 👆🏾 again with fjage-sentuator (`dev`) and `fjage-1.9.1`

```
{"action":"send","message":{"clazz":"org.arl.fjage.sentuator.GenericMeasurement","data":{"values":{"x":{"value":0.543882035126966,"units":"m"}},"id":null,"type":"Demo Sentuator","time":1632707435095,"msgID":"4429a52a-0430-4b18-a6d2-be0f921ccad8","perf":"INFORM","recipient":"#mysen__ntf","sender":"mysen","inReplyTo":null,"sentAt":1632707435095}},"relay":false}
{"action":"send","message":{"clazz":"org.arl.fjage.sentuator.GenericMeasurement","data":{"values":{"x":{"value":0.01481695369701408,"units":"m"}},"id":null,"type":"Demo Sentuator","time":1632707436093,"msgID":"de895401-06c5-4d53-9092-efc3374ee0cc","perf":"INFORM","recipient":"#mysen__ntf","sender":"mysen","inReplyTo":null,"sentAt":1632707436093}},"relay":false}
```

Looks good!

**Comment by ngyewch** [comment] 2021-09-27 03:35
Looks good!

**Closed** 2021-09-27 16:57 UTC
Labels: bug
